import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QFont
import threading
class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName("Form")
        Form.resize(592, 451)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.line = QFrame(Form)
        self.line.setObjectName("line")
        self.line.setGeometry(QRect(0, 130, 591, 21))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(Form)
        self.line_2.setObjectName("line_2")
        self.line_2.setGeometry(QRect(220, 0, 16, 431))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.frame = QFrame(Form)
        self.frame.setObjectName("frame")
        self.frame.setGeometry(QRect(0, 0, 231, 141))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_35 = QLabel(self.frame)
        self.label_35.setObjectName("label_35")
        self.label_35.setGeometry(QRect(10, 30, 81, 16))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(False)
        font1.setWeight(50)
        self.label_35.setFont(font1)
        self.label_36 = QLabel(self.frame)
        self.label_36.setObjectName("label_36")
        self.label_36.setGeometry(QRect(90, 90, 131, 16))
        self.label_36.setFont(font1)
        self.label_37 = QLabel(self.frame)
        self.label_37.setObjectName("label_37")
        self.label_37.setGeometry(QRect(90, 70, 131, 16))
        self.label_37.setFont(font1)
        self.label_38 = QLabel(self.frame)
        self.label_38.setObjectName("label_38")
        self.label_38.setGeometry(QRect(10, 50, 81, 16))
        self.label_38.setFont(font1)
        self.label_39 = QLabel(self.frame)
        self.label_39.setObjectName("label_39")
        self.label_39.setGeometry(QRect(10, 90, 81, 16))
        self.label_39.setFont(font1)
        self.label_40 = QLabel(self.frame)
        self.label_40.setObjectName("label_40")
        self.label_40.setGeometry(QRect(10, 10, 131, 16))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        font2.setUnderline(True)
        font2.setWeight(75)
        self.label_40.setFont(font2)
        self.label_41 = QLabel(self.frame)
        self.label_41.setObjectName("label_41")
        self.label_41.setGeometry(QRect(90, 50, 131, 16))
        self.label_41.setFont(font1)
        self.label_42 = QLabel(self.frame)
        self.label_42.setObjectName("label_42")
        self.label_42.setGeometry(QRect(10, 110, 81, 16))
        self.label_42.setFont(font1)
        self.label_43 = QLabel(self.frame)
        self.label_43.setObjectName("label_43")
        self.label_43.setGeometry(QRect(90, 30, 131, 16))
        self.label_43.setFont(font1)
        self.label_44 = QLabel(self.frame)
        self.label_44.setObjectName("label_44")
        self.label_44.setGeometry(QRect(10, 70, 81, 16))
        self.label_44.setFont(font1)
        self.label_45 = QLabel(self.frame)
        self.label_45.setObjectName("label_45")
        self.label_45.setGeometry(QRect(90, 110, 131, 16))
        self.label_45.setFont(font1)
        self.frame_2 = QFrame(Form)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.setGeometry(QRect(280, 0, 271, 141))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_28 = QLabel(self.frame_2)
        self.label_28.setObjectName("label_28")
        self.label_28.setGeometry(QRect(180, 80, 41, 16))
        self.label_28.setFont(font1)
        self.label_27 = QLabel(self.frame_2)
        self.label_27.setObjectName("label_27")
        self.label_27.setGeometry(QRect(180, 60, 41, 16))
        self.label_27.setFont(font1)
        self.label_25 = QLabel(self.frame_2)
        self.label_25.setObjectName("label_25")
        self.label_25.setGeometry(QRect(230, 60, 41, 16))
        self.label_25.setFont(font1)
        self.label_22 = QLabel(self.frame_2)
        self.label_22.setObjectName("label_22")
        self.label_22.setGeometry(QRect(50, 80, 41, 16))
        self.label_22.setFont(font1)
        self.label_23 = QLabel(self.frame_2)
        self.label_23.setObjectName("label_23")
        self.label_23.setGeometry(QRect(230, 80, 41, 16))
        self.label_23.setFont(font1)
        self.label_26 = QLabel(self.frame_2)
        self.label_26.setObjectName("label_26")
        self.label_26.setGeometry(QRect(230, 40, 41, 16))
        self.label_26.setFont(font1)
        self.label_18 = QLabel(self.frame_2)
        self.label_18.setObjectName("label_18")
        self.label_18.setGeometry(QRect(50, 40, 41, 16))
        self.label_18.setFont(font1)
        self.label_24 = QLabel(self.frame_2)
        self.label_24.setObjectName("label_24")
        self.label_24.setGeometry(QRect(180, 40, 41, 16))
        self.label_24.setFont(font1)
        self.label_17 = QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.label_17.setGeometry(QRect(0, 40, 41, 16))
        self.label_17.setFont(font1)
        self.label_20 = QLabel(self.frame_2)
        self.label_20.setObjectName("label_20")
        self.label_20.setGeometry(QRect(50, 60, 41, 16))
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.label_12.setGeometry(QRect(80, 10, 131, 16))
        self.label_12.setFont(font2)
        self.label_21 = QLabel(self.frame_2)
        self.label_21.setObjectName("label_21")
        self.label_21.setGeometry(QRect(0, 80, 41, 16))
        self.label_21.setFont(font1)
        self.pushButton = QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setGeometry(QRect(80, 110, 121, 23))
        self.pushButton.setFont(font1)
        self.label_19 = QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.label_19.setGeometry(QRect(0, 60, 41, 16))
        self.label_19.setFont(font1)
        self.frame_3 = QFrame(Form)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.setGeometry(QRect(230, 140, 361, 281))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_15 = QLabel(self.frame_3)
        self.label_15.setObjectName("label_15")
        self.label_15.setGeometry(QRect(130, 10, 131, 16))
        self.label_15.setFont(font2)
        self.frame_4 = QFrame(self.frame_3)
        self.frame_4.setObjectName("frame_4")
        self.frame_4.setGeometry(QRect(10, 30, 341, 231))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.line_3 = QFrame(Form)
        self.line_3.setObjectName("line_3")
        self.line_3.setGeometry(QRect(0, 420, 591, 21))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.frame_5 = QFrame(Form)
        self.frame_5.setObjectName("frame_5")
        self.frame_5.setGeometry(QRect(0, 140, 231, 281))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.label_16 = QLabel(self.frame_5)
        self.label_16.setObjectName("label_16")
        self.label_16.setGeometry(QRect(10, 10, 161, 16))
        self.label_16.setFont(font2)
        self.label_32 = QLabel(self.frame_5)
        self.label_32.setObjectName("label_32")
        self.label_32.setGeometry(QRect(100, 220, 121, 20))
        self.label_32.setFont(font1)
        self.label_31 = QLabel(self.frame_5)
        self.label_31.setObjectName("label_31")
        self.label_31.setGeometry(QRect(10, 250, 81, 16))
        self.label_31.setFont(font1)
        self.label_11 = QLabel(self.frame_5)
        self.label_11.setObjectName("label_11")
        self.label_11.setGeometry(QRect(10, 70, 81, 16))
        self.label_11.setFont(font1)
        self.label_10 = QLabel(self.frame_5)
        self.label_10.setObjectName("label_10")
        self.label_10.setGeometry(QRect(10, 40, 81, 16))
        self.label_10.setFont(font1)
        self.pushButton_2 = QPushButton(self.frame_5) #backend will be here <<----
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setGeometry(QRect(40, 130, 141, 23))
        self.pushButton_2.setFont(font1)
        self.label_29 = QLabel(self.frame_5)
        self.label_29.setObjectName("label_29")
        self.label_29.setGeometry(QRect(10, 220, 81, 16))
        self.label_29.setFont(font1)
        self.label_34 = QLabel(self.frame_5)
        self.label_34.setObjectName("label_34")
        self.label_34.setGeometry(QRect(170, 230, 51, 20))
        self.label_34.setFont(font1)
        self.comboBox_2 = QComboBox(self.frame_5)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.setGeometry(QRect(90, 70, 131, 22))
        self.comboBox_2.setFont(font1)
        self.pushButton_4 = QPushButton(self.frame_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setGeometry(QRect(50, 190, 121, 23))
        self.pushButton_4.setFont(font1)
        self.pushButton_3 = QPushButton(self.frame_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setGeometry(QRect(50, 160, 121, 23))
        self.pushButton_3.setFont(font1)
        self.comboBox = QComboBox(self.frame_5)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setGeometry(QRect(90, 40, 131, 22))
        self.comboBox.setFont(font1)
        self.label_53 = QLabel(self.frame_5)
        self.label_53.setObjectName("label_53")
        self.label_53.setGeometry(QRect(10, 100, 81, 16))
        self.label_53.setFont(font1)
        self.comboBox_5 = QComboBox(self.frame_5)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.setGeometry(QRect(90, 100, 131, 22))
        self.comboBox_5.setFont(font1)
        self.label_33 = QLabel(self.frame_5)
        self.label_33.setObjectName("label_33")
        self.label_33.setGeometry(QRect(100, 250, 121, 20))
        self.label_33.setFont(font1)
        self.label_HardwareConnection = QLabel(Form)
        self.label_HardwareConnection.setObjectName("label_HardwareConnection")
        self.label_HardwareConnection.setGeometry(QRect(400, 430, 181, 20))
        self.label_HardwareConnection.setFont(font1)

        self.pushButton_4.clicked.connect(self.stop_therapy)
        self.pushButton_3.clicked.connect(self.start_therapy)
        #self.pushButton_2.clicked.connect(self.workerThread.start_data_retrieval)
        
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_timer)
        self.timer_running = False
        self.elapsed_time = QTime(0, 0)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def start_therapy(self):
        confirm = QMessageBox.question(
            None, "Start Therapy", "Are you sure you want to start therapy?",
            QMessageBox.Yes | QMessageBox.No
        )

        if confirm == QMessageBox.Yes:
            self.timer_running = True
            self.timer.start(1000)  # Start timer with 1-second intervals
            self.elapsed_time = QTime(0, 0)
            self.update_timer()

    def stop_therapy(self):
        confirm = QMessageBox.question(
            None, "Stop Therapy", "Are you sure you want to stop therapy?",
            QMessageBox.Yes | QMessageBox.No
        )

        if confirm == QMessageBox.Yes:
            self.timer_running = False
            self.timer.stop()
            self.elapsed_time = QTime(0, 0)
            self.update_timer()

    def update_timer(self):
        if self.timer_running:
            self.elapsed_time = self.elapsed_time.addSecs(1)
            self.label_HardwareConnection.setText("Therapy Running: " + self.elapsed_time.toString("hh:mm:ss"))
        else:
            self.label_HardwareConnection.setText("Therapy Stopped")

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", "Therapy", None))
        self.label_35.setText(QCoreApplication.translate("Form", "Patient ID :", None))
        self.label_36.setText("")
        self.label_37.setText("")
        self.label_38.setText(QCoreApplication.translate("Form", "Patient's Name :", None))
        self.label_39.setText(QCoreApplication.translate("Form", "Gender :", None))
        self.label_40.setText(QCoreApplication.translate("Form", "Patient's Details", None))
        self.label_41.setText("")
        self.label_42.setText(QCoreApplication.translate("Form", "Blood Group :", None))
        self.label_43.setText("")
        self.label_44.setText(QCoreApplication.translate("Form", "Age :", None))
        self.label_45.setText("")
        self.label_28.setText(QCoreApplication.translate("Form", "Data 6 :", None))
        self.label_27.setText(QCoreApplication.translate("Form", "Data 5 :", None))
        self.label_25.setText("")
        self.label_22.setText("")
        self.label_23.setText("")
        self.label_26.setText("")
        self.label_18.setText("")
        self.label_24.setText(QCoreApplication.translate("Form", "Data 4 :", None))
        self.label_17.setText(QCoreApplication.translate("Form", "Data 1 :", None))
        self.label_20.setText("")
        self.label_12.setText(QCoreApplication.translate("Form", "Therapy Details", None))
        self.label_21.setText(QCoreApplication.translate("Form", "Data 3 :", None))
        self.pushButton.setText(QCoreApplication.translate("Form", "See 3D Visualization", None))
        self.label_19.setText(QCoreApplication.translate("Form", "Data 2 :", None))
        self.label_15.setText(QCoreApplication.translate("Form", "3D Visualization", None))
        self.label_16.setText(QCoreApplication.translate("Form", "Therapy Controller", None))
        self.label_32.setText("")
        # self.label_31.setText(QCoreApplication.translate("Form", "Session Time :", None))
        self.label_11.setText(QCoreApplication.translate("Form", "Mode :", None))
        self.label_10.setText(QCoreApplication.translate("Form", "Arm :", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", "Connect with Hardware", None))
        # self.label_29.setText(QCoreApplication.translate("Form", "Therapy Status :", None))
        # self.label_34.setText("")
        self.comboBox_2.setItemText(0, QCoreApplication.translate("Form", "Active", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("Form", "Passive", None))

        self.pushButton_4.setText(QCoreApplication.translate("Form", "Stop Therapy", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", "Start Therapy", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Form", "Right", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Form", "Left", None))

        self.label_53.setText(QCoreApplication.translate("Form", "Type :", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("Form", "Armpit stretch", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("Form", "Finger walk", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("Form", "Forward flexion", None))
        self.comboBox_5.setItemText(3, QCoreApplication.translate("Form", "Inward rotation", None))
        self.comboBox_5.setItemText(4, QCoreApplication.translate("Form", "Neck stretches", None))
        self.comboBox_5.setItemText(5, QCoreApplication.translate("Form", "Pendulum stretch", None))
        self.comboBox_5.setItemText(6, QCoreApplication.translate("Form", "Scapular Retractions", None))
        self.comboBox_5.setItemText(7, QCoreApplication.translate("Form", "Towel stretch", None))

        self.label_33.setText("")
        self.label_HardwareConnection.setText("")
#Help me to run the UI and the serial communication in parallel


if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

